version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: postgres:14-bullseye
    environment:
      POSTGRES_PASSWORD: password
